on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      # https://github.com/actions/setup-go/tags
      uses: actions/setup-go@v5
      # https://github.com/actions/checkout/tags
    - uses: actions/checkout@v4
      with:
         path: './src/github.com/kevinburke/go-html-boilerplate'
    # staticcheck needs this for GOPATH
    - run: |
        echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "GO111MODULE=off" >> $GITHUB_ENV
        echo "PATH=$GITHUB_WORKSPACE/bin:$PATH" >> $GITHUB_ENV
    - name: Run tests
      run: |
        GO111MODULE=on go install honnef.co/go/tools/cmd/staticcheck@latest
        make test
      working-directory: './src/github.com/kevinburke/go-html-boilerplate'
